export { default as Favorite } from "./Favourites/Favourites";
export { default as Category } from "./Category/Category";
export { default as AboutUs } from "./AboutUs/AboutUs";
export { default as Main } from "./Main/Main";
export { default as Products } from "./Products/Products";
export { default as NewsCart } from "./NewsCart/NewsCart";
export { default as Delivery } from "./Delivery/Delivery";
export { default as PageNotFound } from "./PageNotFound/PageNotFound";
export { default as Favourites } from "./Favourites/Favourites";
